spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/password
    username: postgres
    password: roo
  jpa:
    database: POSTGRESQL
    show_sql: false
    format_sql: true
    hibernate:
      ddl-auto: validate
